// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vertr.Market.DataAccess;

#nullable disable

namespace Vertr.Market.DataAccess.Migrations
{
    [DbContext(typeof(MarketDataDbContext))]
    [Migration("20260314233817_MarketDataTables01")]
    partial class MarketDataTables01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vertr.Market.DataAccess.Dbos.MarketTradeDbo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<string>("JsonContent")
                        .HasColumnType("jsonb")
                        .HasColumnName("json_content");

                    b.Property<DateTime>("TimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_utc");

                    b.HasKey("Id")
                        .HasName("market_trades_pkey");

                    b.ToTable("market_trades", (string)null);
                });

            modelBuilder.Entity("Vertr.Market.DataAccess.Dbos.OpenInterestDbo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<string>("JsonContent")
                        .HasColumnType("jsonb")
                        .HasColumnName("json_content");

                    b.Property<DateTime>("TimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_utc");

                    b.HasKey("Id")
                        .HasName("open_interests_pkey");

                    b.ToTable("open_interests", (string)null);
                });

            modelBuilder.Entity("Vertr.Market.DataAccess.Dbos.OrderBookDbo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<string>("JsonContent")
                        .HasColumnType("jsonb")
                        .HasColumnName("json_content");

                    b.Property<DateTime>("TimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_utc");

                    b.HasKey("Id")
                        .HasName("order_books_pkey");

                    b.ToTable("order_books", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
