services:
  vertr-market:
    build:
      context: .
    ports:
      - "8085:8080"
    networks:
      - vertr-infrastructure_infra
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker 

networks:
  vertr-infrastructure_infra:
    external: true
    driver: bridge