services:

  host:
    image: vertr_market_host_image
    build:
      context: .
      dockerfile: src/Market.Host/Dockerfile
    ports:
      - "7001:8080"
      - "7005:5005"
    networks:
      - vertr-infrastructure_infra
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker 
      - ASPNETCORE_URLS=http://0.0.0

  tinvest:
    image: vertr_market_gateways_tinvest_image
    build:
      context: .
      dockerfile: src/Market.Gateways.Tinvest/Dockerfile
    ports:
      - "7002:8080"
    networks:
      - vertr-infrastructure_infra
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker 

networks:
  vertr-infrastructure_infra:
    external: true
    driver: bridge
