global:
  scrape_interval: 5s # Частота сбора метрик

scrape_configs:
  - job_name: 'vertr-market-tinvest'
    scrape_interval: 1s
    metrics_path: '/metrics' 
    static_configs:
      - targets: ['vertr-market-tinvest-1:8080']  
  - job_name: 'vertr-market-host'
    scrape_interval: 1s
    metrics_path: '/metrics' 
    static_configs:
      - targets: ['vertr-market-host-1:8080']  
